version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mining-db
      POSTGRES_USER: marctheshark
      POSTGRES_PASSWORD: password
    volumes:
      - mining_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5431:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile.all  # Make sure this is the name of your Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8050:8050"
    restart: unless-stopped
    depends_on:
      - db

volumes:
  mining_data:
