version: '3.8'
services:
  ui:
    image: ghcr.io/marctheshark3/sigmanaut-mining-pool-ui:main
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8050:8050"
    restart: unless-stopped
    
  miner-id-minter:
    build:
      context: ./off-chain
      dockerfile: Dockerfile
    volumes:
      - ./off-chain:/app
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - ui

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # Add HTTPS port
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro

    depends_on:
      - ui
    restart: unless-stopped
